version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - vectorstore_data:/app/data
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./client:/app
    depends_on:
      - server
    restart: unless-stopped

volumes:
  vectorstore_data:
